{
   type: "supportcase",
   isDynamic: false,
   fields: {
      isinactive: "F",
      wfinstances: "",
      nlloc: "0",
      nlsub: "2",
      custpage_rac_preloadedtransactionstring: "{"selecttransactionlinepage.message.deletewarningbanner.title":"Note","selecttransactionlinepage.message.deletewarningbanner.message":"Deleting this case record will not delete any associated Return Authorization or Replacement Sales Order."}",
      origin: "1",
      incomingmessage: '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http: //schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">\r\n<meta name="Generator" content="Microsoft Word 15 (filtered medium)">\r\n<style><!--\r\n/* Font Definitions */\r\n@font-face\r\n\t{font-family:"Cambria Math";\r\n\tpanose-1:2 4 5 3 5 4 6 3 2 4;}\r\n@font-face\r\n\t{font-family:Calibri;\r\n\tpanose-1:2 15 5 2 2 2 4 3 2 4;}\r\n/* Style Definitions */\r\np.MsoNormal, li.MsoNormal, div.MsoNormal\r\n\t{margin:0in;\r\n\tfont-size:10.0pt;\r\n\tfont-family:"Calibri",sans-serif;}\r\na:link, span.MsoHyperlink\r\n\t{mso-style-priority:99;\r\n\tcolor:blue;\r\n\ttext-decoration:underline;}\r\nspan.EmailStyle18\r\n\t{mso-style-type:personal-reply;\r\n\tfont-family:"Calibri",sans-serif;\r\n\tcolor:windowtext;}\r\n.MsoChpDefault\r\n\t{mso-style-type:export-only;\r\n\tfont-size:10.0pt;}\r\n@page WordSection1\r\n\t{size:8.5in 11.0in;\r\n\tmargin:1.0in 1.0in 1.0in 1.0in;}\r\ndiv.WordSection1\r\n\t{page:WordSection1;}\r\n--></style>\r\n</head>\r\n<body lang="EN-US" link="blue" vlink="purple" style="word-wrap:break-word">\r\n<div class="WordSection1">\r\n<p class="MsoNormal"><span style="font-size:11.0pt">Test forwarded case email<o:p></o:p></span></p>\r\n<p class="MsoNormal"><span style="font-size:11.0pt"><o:p> </o:p></span></p>\r\n<p class="MsoNormal" style="mso-margin-top-alt:auto;mso-margin-bottom-alt:auto"><b><span style="font-size:14.0pt;color:#1A3D6E">Zachary Oliver</span></b><span style="font-size:11.0pt;color:#3C3C3B"><br>\r\nO: 916-526-0749</span><span style="font-size:11.0pt"><o:p></o:p></span></p>\r\n<p class="MsoNormal"><span style="font-size:11.0pt"><o:p> </o:p></span></p>\r\n<p class="MsoNormal"><span style="font-size:11.0pt"><o:p> </o:p></span></p>\r\n<div style="border:none;border-top:solid #B5C4DF 1.0pt;padding:3.0pt 0in 0in 0in">\r\n<p class="MsoNormal" style="margin-bottom:12.0pt"><b><span style="font-size:12.0pt;color:black">From:\r\n</span></b><span style="font-size:12.0pt;color:black">Zachary Oliver <zachjoliver@gmail.com><br>\r\n<b>Date: </b>Friday, July 8, 2022 at 11:38 AM<br>\r\n<b>To: </b>Zachary Oliver <ZOliver@Velosio.com><br>\r\n<b>Subject: </b>Case Creation to Forward<o:p></o:p></span></p>\r\n</div>\r\n<div style="border:solid #9C6500 1.0pt;padding:2.0pt 2.0pt 2.0pt 2.0pt">\r\n<p class="MsoNormal" style="line-height:12.0pt;background:#FFEB9C"><b><span style="color:black">[Ext Email]</span></b><span style="color:black"><o:p></o:p></span></p>\r\n</div>\r\n<div>\r\n<div>\r\n<p class="MsoNormal"><span style="font-size:11.0pt">Email: <a href="mailto:new@test.com">\r\nnew@test.com</a><o:p></o:p></span></p>\r\n</div>\r\n</div>\r\n</div>\r\n</body>\r\n</html>\r\n',
      _eml_nkey_: "3624332_SB2~-4~3~N",
      starttime: "11:41 am",
      emailform: "F",
      type: "case",
      startdate: "7/8/2022",
      title: "FW: Case Creation to Forward",
      nsapiCT: "1657305693678",
      sys_id: "-2196605257276989",
      casenumber: "To Be Generated",
      nluser: "2852",
      nldept: "0",
      company: "2852",
      email: "ZOliver@Velosio.com",
      internalonly: "F",
      templatestored: "F",
      profile: "1",
      nlrole: "3",
      inboundemail: "cases.3624332_SB2.81db967822@3624332-sb2.email.netsuite.com",
      baserecordtype: "supportcase",
      priority: "2",
      customform: "182",
      stage: "OPEN",
      emailemployees: "",
      status: "1"
  }
}